In [1]:
import pandas as pd
import os
from datetime import datetime

In [49]:
data_files = os.listdir('../csv_downloads/weather')
data_files

['POWER_Point_Hourly_20200901_20200930_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20210601_20210630_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20190701_20190731_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20201001_20201031_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20200401_20200430_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20190501_20190531_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20200201_20200229_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20191101_20191130_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20210401_20210430_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20200601_20200630_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20210201_20210228_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20190801_20190831_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20201201_20201231_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20200301_20200331_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20190901_20190930_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20200701_20200731_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20191001_20191031_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20210501_20210531_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20190322_20190430_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20210101_20210131_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20200501_20200531_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20210801_20210826_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20200101_20200131_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20201101_20201130_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20190601_20190630_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20210301_20210331_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20210701_20210731_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20191201_20191231_044d9591N_093d2878W_LST.csv',
 'POWER_Point_Hourly_20200801_20200831_044d9591N_093d2878W_LST.csv']

In [52]:
def load_files(data_files):
    for file in data_files:
        yield(
            pd.read_csv('../csv_downloads/weather/' + file,
            header=20,
            parse_dates= {"Time" : ["YEAR","MO","DY","HR"]},
                keep_date_col=True
            ) 
        )

In [53]:
weather_data = pd.concat(load_files(data_files))
weather_data

,Time,YEAR,MO,DY,HR,ALLSKY_SFC_SW_DWN,ALLSKY_KT,ALLSKY_SRF_ALB,SZA,ALLSKY_SFC_PAR_TOT,ALLSKY_SFC_UVA,ALLSKY_SFC_UVB,ALLSKY_SFC_UV_INDEX,T2M,RH2M,PS,WD10M
0,2020 9 1 0,2020,9,1,0,0.0,-999.0,-999.0,90.0,0.0,0.0,0.0,0.0,11.99,76.94,98.05,277.50
1,2020 9 1 1,2020,9,1,1,0.0,-999.0,-999.0,90.0,0.0,0.0,0.0,0.0,11.79,77.75,98.05,264.52
2,2020 9 1 2,2020,9,1,2,0.0,-999.0,-999.0,90.0,0.0,0.0,0.0,0.0,11.38,79.44,98.04,252.43
3,2020 9 1 3,2020,9,1,3,0.0,-999.0,-999.0,90.0,0.0,0.0,0.0,0.0,11.15,80.62,98.01,242.06
4,2020 9 1 4,2020,9,1,4,0.0,-999.0,-999.0,90.0,0.0,0.0,0.0,0.0,10.70,82.88,97.99,229.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,2020 8 31 19,2020,8,31,19,0.0,-999.0,-999.0,90.0,0.0,0.0,0.0,0.0,13.58,73.56,97.90,282.99
740,2020 8 31 20,2020,8,31,20,0.0,-999.0,-999.0,90.0,0.0,0.0,0.0,0.0,13.15,73.38,97.94,281.25
741,2020 8 31 21,2020,8,31,21,0.0,-999.0,-999.0,90.0,0.0,0.0,0.0,0.0,12.61,74.19,97.95,284.89
742,2020 8 31 22,2020,8,31,22,0.0,-999.0,-999.0,90.0,0.0,0.0,0.0,0.0,12.14,75.44,98.00,287.86
743,2020 8 31 23,2020,8,31,23,0.0,-999.0,-999.0,90.0,0.0,0.0,0.0,0.0,11.93,76.12,98.04,285.27

In [56]:
pd.to_datetime(weather_data['Time'])

ParserError: Unknown string format: 2020 9 1 0

In [33]:
output_files = os.listdir('../csv_downloads/solar_output')
output_files

['19_production.csv', '21_production.csv', '20_production.csv']

In [34]:
def load_output(output_files):
    for file in output_files:
        yield(
            pd.read_csv('../csv_downloads/solar_output/' + file
            ) 
        )

In [35]:
output_data = pd.concat(load_output(output_files))
output_data

                  Time  Energy (Wh)
0     03/22/2019 07:00          124
1     03/22/2019 08:00         1437
2     03/22/2019 09:00         2602
3     03/22/2019 10:00         4759
4     03/22/2019 11:00         6529
...                ...          ...
4994  12/31/2020 13:00            0
4995  12/31/2020 14:00            0
4996  12/31/2020 15:00            0
4997  12/31/2020 16:00            0
4998  12/31/2020 22:00            0

[12432 rows x 2 columns]

In [48]:
pd.to_datetime(weather_data[['YEAR','MO','DY','HR']])

ValueError: to assemble mappings requires at least that [year, month, day] be specified: [day,month] is missing

In [44]:
weather_data['new_col'] = pd.to_datetime(weather_data[['YEAR','MO','DY','HR']])
# df['Date']=pd.to_datetime(df[['year','month','day']])
weather_data

ValueError: to assemble mappings requires at least that [year, month, day] be specified: [day,month] is missing

In [54]:
print(weather_data.dtypes)
print(output_data.dtypes)

Time                    object
YEAR                    object
MO                      object
DY                      object
HR                      object
ALLSKY_SFC_SW_DWN      float64
ALLSKY_KT              float64
ALLSKY_SRF_ALB         float64
SZA                    float64
ALLSKY_SFC_PAR_TOT     float64
ALLSKY_SFC_UVA         float64
ALLSKY_SFC_UVB         float64
ALLSKY_SFC_UV_INDEX    float64
T2M                    float64
RH2M                   float64
PS                     float64
WD10M                  float64
dtype: object
Time           object
Energy (Wh)     int64
dtype: object